# Generated by Django 4.2.18 on 2025-02-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='one_click_purshasing',
            new_name='one_click_purchasing',
        ),
    ]
