# Generated by Django 4.2.18 on 2025-02-06 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_orderitem_orderitem_quantity_gte_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street Address')),
                ('apartment_address', models.CharField(max_length=100, verbose_name='Apartment Address')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('zip', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1, verbose_name='Address Type')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
