# Generated by Django 4.2.18 on 2025-02-06 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_stripe_customer_id_userprofile_payment_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Code must be 4 to 15 characters long and contain only uppercase letters and numbers.', regex='^[A-Z0-9]{4,15}$')])),
                ('amount', models.FloatField()),
            ],
        ),
    ]
