# Generated by Django 4.2.18 on 2025-02-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_user_id_7537a5_idx',
        ),
    ]
